project_id = "euijfoczbexcikdylvpm"

[functions.send-signing-email]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.dispatch-webhook]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.bluepoint-proxy]
verify_jwt = false

[functions.bluetech-proxy]
verify_jwt = false