project_id = "euijfoczbexcikdylvpm"

[functions.send-signing-email]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.dispatch-webhook]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.bluepoint-proxy]
verify_jwt = false

[functions.bluetech-proxy]
verify_jwt = false

[functions.validar-download]
verify_jwt = false

[functions.gerar-documento-final]
verify_jwt = false

[functions.processar-assinatura]
verify_jwt = false

[functions.reprocessar-pendentes]
verify_jwt = false